<?php	

	if($command=='ALTER_TABLE_PROCESS_NEW_GMIS'){
		$strSQL = " SELECT COUNT(a.CONFIG_NAME) AS CNT  from SYSTEM_CONFIG a 
									WHERE  a.CONFIG_NAME = 'GMIS_START_TIME_PROCESS' 
									   OR  a.CONFIG_NAME = 'GMIS_END_TIME_PROCESS'
									   OR  a.CONFIG_NAME = 'GMIS_STATUS_PROCESS' ";
		$db->send_cmd($strSQL);
		$data = $db->get_array();
		if($data[CNT]==0){
			$chk = "";
			if(true){
				$cmdM = "SELECT MAX(CONFIG_ID) AS MAXOFCONFIG_ID FROM SYSTEM_CONFIG";
				$db->send_cmd($cmdM);
				$dataMax = $db->get_array();
				$MAXOFCONFIG_ID =  $dataMax[MAXOFCONFIG_ID]+1;
					
				$strSQL_INSERT_GMSTART = " 	INSERT INTO SYSTEM_CONFIG (CONFIG_ID, CONFIG_NAME, CONFIG_VALUE, CONFIG_REMARK) 
							VALUES ($MAXOFCONFIG_ID, 'GMIS_START_TIME_PROCESS', '', 'วัน-เวลาที่เริ่มประมวลผล  GMIS') ";
							
				$db->send_cmd($strSQL_INSERT_GMSTART);
				if($db->ERRNO.$db->ERROR != 0){
					$chk .= $db->ERRNO.$db->ERROR;
				}
			}
			
			if(!$chk){
				$cmdM = "SELECT MAX(CONFIG_ID) AS MAXOFCONFIG_ID FROM SYSTEM_CONFIG";
				$db->send_cmd($cmdM);
				$dataMax = $db->get_array();
				$MAXOFCONFIG_ID =  $dataMax[MAXOFCONFIG_ID]+1;
				
				$strSQL_INSERT_GMEND = " 	INSERT INTO SYSTEM_CONFIG (CONFIG_ID, CONFIG_NAME, CONFIG_VALUE, CONFIG_REMARK) 
						VALUES ($MAXOFCONFIG_ID, 'GMIS_END_TIME_PROCESS', '', 'วัน-เวลาที่ประมวลผลสำเร็จ GMIS') ";
				$db->send_cmd($strSQL_INSERT_GMEND);
				if($db->ERRNO.$db->ERROR != 0){
					$chk .= $db->ERRNO.$db->ERROR;
				}
			}
			
			if(!$chk){
				//echo "2 TRUE<br>";
				$cmdM = "SELECT MAX(CONFIG_ID) AS MAXOFCONFIG_ID FROM SYSTEM_CONFIG";
				$db->send_cmd($cmdM);
				$dataMax = $db->get_array();
				$MAXOFCONFIG_ID =  $dataMax[MAXOFCONFIG_ID]+1;
				
				$strSQL_INSERT_GMSTATUS = " INSERT INTO SYSTEM_CONFIG (CONFIG_ID, CONFIG_NAME, CONFIG_VALUE, CONFIG_REMARK) 
						VALUES ($MAXOFCONFIG_ID, 'GMIS_STATUS_PROCESS', '', 'สถานะการทำงาน GMIS') ";
				//echo $strSQL_INSERT_GMSTATUS;
				$db->send_cmd($strSQL_INSERT_GMSTATUS);
				if($db->ERRNO.$db->ERROR != 0){
					$chk .= $db->ERRNO.$db->ERROR;
				}
			}
			
			if(!$chk){
				$strSQL_DROP = " DROP TABLE GMIS_GPIS ";
				$db_dpis2->send_cmd($strSQL_DROP);
			}	
			
			if(!$chk){
				$strSQL_CREATE_TABLE = "
							CREATE TABLE GMIS_GPIS (
								TEMPMINISTRY VARCHAR2(100 BYTE),
								TEMPORGANIZE VARCHAR2(100 BYTE),
								TEMPDIVISIONNAME VARCHAR2(100 BYTE),
								TEMPORGANIZETYPE VARCHAR2(50 BYTE),
								TEMPPOSITIONNO VARCHAR2(20 BYTE),
								TEMPMANAGEPOSITION VARCHAR2(100 BYTE),
								TEMPLINE VARCHAR2(100 BYTE),
								TEMPPOSITIONTYPE VARCHAR2(20 BYTE),
								TEMPLEVEL VARCHAR2(100 BYTE),
								TEMPCLNAME VARCHAR2(100 BYTE),
								TEMPSKILL VARCHAR2(100 BYTE),
								TEMPCOUNTRY VARCHAR2(50 BYTE),
								TEMPPROVINCE VARCHAR2(50 BYTE),
								TEMPPOSITIONSTATUS VARCHAR2(20 BYTE),
								TEMPCLASS VARCHAR2(30 BYTE),
								TEMPPRENAME VARCHAR2(30 BYTE),
								TEMPFIRSTNAME VARCHAR2(50 BYTE),
								TEMPLASTNAME VARCHAR2(50 BYTE),
								TEMPCARDNO VARCHAR2(13 BYTE),
								TEMPGENDER VARCHAR2(10 BYTE),
								TEMPSTATUSDISABILITY VARCHAR2(10 BYTE),
								TEMPRELIGION VARCHAR2(20 BYTE),
								TEMPBIRTHDATE VARCHAR2(10 BYTE),
								TEMPSALARY NUMBER(10, 2),
								TEMPPOSITIONSALARY NUMBER(10, 2),
								TEMPEDUCATIONLEVEL VARCHAR2(100 BYTE),
								TEMPEDUCATIONNAME VARCHAR2(100 BYTE),
								TEMPEDUCATIONMAJOR VARCHAR2(100 BYTE),
								TEMPGRADUATED VARCHAR2(100 BYTE),
								TEMPEDUCATIONCOUNTRY VARCHAR2(50 BYTE),
								TEMPSCHOLARTYPE VARCHAR2(100 BYTE),
								TEMPMOVEMENTTYPE VARCHAR2(100 BYTE),
								TEMPMOVEMENTDATE VARCHAR2(10 BYTE),
								TEMPSTARTDATE VARCHAR2(10 BYTE),
								TEMPFLOWDATE VARCHAR2(10 BYTE),
								TEMPRESIGNDATE VARCHAR2(10 BYTE),
								TEMPPROMOTEDATE VARCHAR2(10 BYTE),
								TEMPDECORATION VARCHAR2(50 BYTE),
								TEMPUNION VARCHAR2(10 BYTE),
								TEMPRESULT1 VARCHAR2(100 BYTE),
								TEMPPERCENTSALARY1 VARCHAR2(10 BYTE),
								TEMPRESULT2 VARCHAR2(100 BYTE),
								TEMPPERCENTSALARY2 VARCHAR2(10 BYTE),
								TEMPMPERSPSKILL1 VARCHAR2(100 BYTE),
								TEMPSPERSPSKILL1 VARCHAR2(100 BYTE),
								TEMPSKILLLEVEL1 VARCHAR2(100 BYTE),
								TEMPPERSPSKILLDES1 VARCHAR2(2000 BYTE),
								TEMPMPERSPSKILL2 VARCHAR2(100 BYTE),
								TEMPSPERSPSKILL2 VARCHAR2(100 BYTE),
								TEMPSKILLLEVEL2 VARCHAR2(100 BYTE),
								TEMPPERSPSKILLDES2 VARCHAR2(2000 BYTE),
								TEMPMPERSPSKILL3 VARCHAR2(100 BYTE),
								TEMPSPERSPSKILL3 VARCHAR2(100 BYTE),
								TEMPSKILLLEVEL3 VARCHAR2(100 BYTE),
								TEMPPERSPSKILLDES3 VARCHAR2(2000 BYTE),
								TEMPSPS_FLAG1 VARCHAR2(100 BYTE),
								TEMPSPS_FLAG2 VARCHAR2(100 BYTE),
								TEMPSPS_FLAG3 VARCHAR2(100 BYTE),
								CONSTRAINT PK_GMIS_GPIS PRIMARY KEY (TEMPPOSITIONNO)
							)
				";
				$db_dpis2->send_cmd($strSQL_CREATE_TABLE);
			}
		}
		$command="";
	}
	
?>